# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ehsan Saleh
title: Machine Learning researcher & Smart Contract developer
email: ehsansaleh155@gmail.com
# website: ehsansaleh155.github.io
skype: live:.cid.410b7f9d5d83fd60

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: EhsanSaleh14
github_username:  ehsansaleh155
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ehsan-saleh-3b7648114
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://ehsansaleh155.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Ehsan Saleh. I'm spending my time in two areas, Artificial Intelligence and Blockchain.  
  Currently, I'm working on using the tricks of Adversarial Machine Learning in VQA (Visual Question Answering) system.  
  I have also been learning and developing DApps in Ethereum and Solana blockchains. My goal is to do research and develop applications to make positive impacts on human society.  
  **Birthyear:** 1998

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tomsk State University
        caption: 2020 - 2022
        sub_title: Master of Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Address:** 36 Lenin Ave. Tomsk, 634050 Tomsk (Russia)  
          **Website:** www.tsu.ru  
          **Field(s) of study:** Information technology in science and instrument engineering  
          **Final grade:** 4.94/5.00  
          **Thesis:** Boosting Adversarial Training in Adversarial Machine Learning  
          Machine Learning  
          Computer Vision and Automation  
          Technology, Quality, and Project management  
      - layout: left
        title: Shahid Beheshti University
        caption: 2016 - 2020
        sub_title: Bachelor of Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Address:** Daneshju Str. Velenjak, 1983969411 Tehran (Iran)  
          **Website:** www.sbu.ac.ir  
          **Field(s) of study:**  Electrical Engineering  
          **Final grade:** 17.69/20.00 (US GPA: 3.86/4.00)  
          **Thesis:** Convergence of IoT and 5G, and a brief study on 6G concepts  
          Telecommunication  
          Digital Electronics  
          Digital Signal Processing  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
